### ISSUE TITLE
[FH-03] Tela Inicial de Usuário FRONT-END

### ISSUE THREAD

**Issue by BrunoWil** [BrunoWil/FastHelpDesk#2]
- [x] Criar Botão Início (Casinha) com início ao lado

- [x] Criar componente de que mostra o nome de usuário

- [x] Criar componente de que mostra a imagem do usuário

- [x] Criar Botão de com nome  incluso Logout

- [x] Criar Botão de (+) de Criar mensagem nova

- [x] Criar Barra Superior

- [x] Criar Fundo

**Comment by Lara-L** [comment]
Issue Finalizada
